### ISSUE TITLE
Webpack config

### ISSUE THREAD

**Issue by dns2316** [dns2316/blog#12]
[Настройка вебпак](https://webpack.js.org/configuration/)
Пропишите конфиг

**Comment by shashkovdanil** [comment]
https://github.com/shashkovdanil/test-app-fastdev
Там есть более менее конфиг с HMR, но только дэв версия, для прода нету

**Comment by shashkovdanil** [comment]
В принципе могу заняться написанием

**Comment by dns2316** [comment]
Ok, займись конфигами пожалуйста 
В чем отличие дева и прода в конфиге вебпака?
И что за [HMR](http://andrewhfarmer.com/webpack-hmr-tutorial/)

**Comment by shashkovdanil** [comment]
hot module replacement

**Comment by dns2316** [comment]
@shashkovdanil написал конфиг
